[build]
builder = "dockerfile"
dockerfilePath = "apps/web/Dockerfile"
watchPatterns = ["apps/web/**"]

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
