[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"
watchPatterns = ["packages/agent/**"]
`
[deploy]
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[env]
# These will be set in Railway dashboard
# OPENAI_API_KEY = 
# PERSONAL_NOTION_API_KEY = 
# PERSONAL_NOTION_DB_ID = 
# BEARER_TOKEN = 
# LIVEPEER_NOTION_API_KEY = (optional)
# LIVEPEER_NOTION_DB_ID = (optional)
# VANQUISH_NOTION_API_KEY = (optional)
# VANQUISH_NOTION_DB_ID = (optional)
