[build]
builder = "dockerfile"
dockerfilePath = "packages/frontend/Dockerfile"
watchPatterns = ["packages/frontend/**"]

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
