[build]
builder = "nixpacks"
buildCommand = "npm run frontend:build"
watchPatterns = ["packages/frontend/**"]

[deploy]
startCommand = "npm run frontend:start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
