[build]
builder = "dockerfile"
dockerfilePath = "packages/frontend/Dockerfile"
watchPatterns = ["packages/frontend/**"]

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "frontend"
source = "."
