[build]
builder = "nixpacks"
buildCommand = "cd packages/frontend && npm ci && npm run build"
watchPatterns = ["packages/frontend/**"]

[deploy]
startCommand = "cd packages/frontend && npm start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
