name: Notion & Motion Task Sync

on:
  # Scheduled runs
  schedule:
    # Run full sync every 15 minutes during work hours (8 AM - 8 PM UTC) 
    - cron: '*/15 8-20 * * 1-5'  # Every 15 minutes, weekdays work hours
    # Run full sync once daily at 6 AM UTC (backup)
    - cron: '0 6 * * *'   # Daily at 6 AM UTC
    
  # Allow manual triggering
  workflow_dispatch:
    inputs:
      mode:
        description: 'Sync mode'
        required: true
        default: 'full'
        type: choice
        options:
          - full
          - test
          - test-real

jobs:
  notion-motion-sync:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          cd packages/jobs
          pip install -r requirements.txt
          
      - name: Determine sync mode
        id: sync-mode
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "mode=${{ github.event.inputs.mode }}" >> $GITHUB_OUTPUT
          else
            # All scheduled runs = full sync
            echo "mode=full" >> $GITHUB_OUTPUT
          fi
      - name: Run Notion sync
        env:
          HUB_NOTION_API_KEY: ${{ secrets.HUB_NOTION_API_KEY }}
          LIVEPEER_NOTION_API_KEY: ${{ secrets.LIVEPEER_NOTION_API_KEY }}
          VANQUISH_NOTION_API_KEY: ${{ secrets.VANQUISH_NOTION_API_KEY }}
          HUB_NOTION_DB_ID: ${{ secrets.HUB_NOTION_DB_ID }}
          LIVEPEER_NOTION_DB_ID: ${{ secrets.LIVEPEER_NOTION_DB_ID }}
          VANQUISH_NOTION_DB_ID: ${{ secrets.VANQUISH_NOTION_DB_ID }}
          HUB_NOTION_USER_ID: ${{ secrets.HUB_NOTION_USER_ID }}
          LIVEPEER_NOTION_USER_ID: ${{ secrets.LIVEPEER_NOTION_USER_ID }}
          VANQUISH_NOTION_USER_ID: ${{ secrets.VANQUISH_NOTION_USER_ID }}
        run: |
          cd packages/jobs/notion
          python notion_sync.py --mode ${{ steps.sync-mode.outputs.mode }}
      - name: Run Motion sync
        env:
          # Motion API
          MOTION_API_KEY: ${{ secrets.MOTION_API_KEY }}
          MOTION_HUB_WORKSPACE_ID: ${{ secrets.MOTION_HUB_WORKSPACE_ID }}
          MOTION_LIVEPEER_WORKSPACE_ID: ${{ secrets.MOTION_LIVEPEER_WORKSPACE_ID }}
          MOTION_VANQUISH_WORKSPACE_ID: ${{ secrets.MOTION_VANQUISH_WORKSPACE_ID }}
          # Notion API (reuse from above)
          HUB_NOTION_API_KEY: ${{ secrets.HUB_NOTION_API_KEY }}
          LIVEPEER_NOTION_API_KEY: ${{ secrets.LIVEPEER_NOTION_API_KEY }}
          VANQUISH_NOTION_API_KEY: ${{ secrets.VANQUISH_NOTION_API_KEY }}
          HUB_NOTION_DB_ID: ${{ secrets.HUB_NOTION_DB_ID }}
          LIVEPEER_NOTION_DB_ID: ${{ secrets.LIVEPEER_NOTION_DB_ID }}
          VANQUISH_NOTION_DB_ID: ${{ secrets.VANQUISH_NOTION_DB_ID }}
          HUB_NOTION_USER_ID: ${{ secrets.HUB_NOTION_USER_ID }}
          LIVEPEER_NOTION_USER_ID: ${{ secrets.LIVEPEER_NOTION_USER_ID }}
          VANQUISH_NOTION_USER_ID: ${{ secrets.VANQUISH_NOTION_USER_ID }}
        run: |
          cd packages/jobs
          python motion/motion_sync.py --mode ${{ steps.sync-mode.outputs.mode }}
          
      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: sync-logs-${{ github.run_id }}
          path: |
            packages/jobs/notion/*.log
            packages/jobs/motion/*.log
          retention-days: 7